### ISSUE TITLE
Issues due to lack of root/boot/vmlinux.uimg

### ISSUE THREAD

**Issue by omgmog** [omgmog/archarm-usb-hp-chromebook-11#49]
This is just because the rootfs has changed and now contains a `vmlinux.kpart` which needs to be written to partition 1.

Currently testing a change to the process to make this work.

**Comment by hitechredneck** [comment]
awesome to read this. ran into the same error today. thank you again for all of your work and attention to this.

**Comment by shdriesner** [comment]
I noticed the same issue.  What changes are you investigating?

I was alerted to this project via your youtube video (https://www.youtube.com/watch?v=j0IbMDxYjfo).  Having recently acquired an HP Chromebook 11 and being a fan of Arch Linux, I am eager to be up and running with a native install, so I was glad to find your video and discover the project on GitHub.

I do know that my chromebook does boot successfully from a 8GB thumb drive when following these installation instructions: http://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook

Note that the above instructions don't seem to require the presence of vmlimuz.uimg or boot.scr.uimg in the file system, rather the only requirement is to write the kernel directly to the boot partition via the command 'dd if=root/boot/vmlinuz.kpart of=/dev/sda1' .

I expect I could use these same instructions to do a native install to the eMMC, but I am interested in contributing to your project to make the process more automated, and I would like to have a deeper knowledge of the boot process, specifically for ARM devices.

I have tried installing to the same thumb drive as before using install.sh (commit 70563b373ae6cae4e5df7546a3822bee061f815a), upon which I also noted that vmlimuz.uimg is missing from rootfs, because the copy to mnt fails.  Upon reboot + Ctrl-U, the boot  from the thumb drive fails in such a way that I have to type 'reset' to reset the CPU and get back to ChromeOS and try again.

Something else I tried was to delete boot.scr.uimg from the thumb drive's root filesystem and the run 'dd if=root/boot/vmlinuz.kpart of=/dev/sda1' to write vmlinuz.kpart directly to the boot partition (similar to the above simplified instructions that worked on this hardware), and upon reboot + Ctrl-U the chromebook does boot into the Linux kernel, but the kernel panics because it can't find init.

I am looking forward to whatever changes you are making to address this, and I am willing to help test.

**Comment by omgmog** [comment]
@shdriesner yep, the process has been simplified a bit since I put the video (and this script) together.

The instructions for the samsung chromebook will work absolutely fine for an installation to USB (/dev/sda, I did this last night following them), and might even work for /dev/mmcblk0, if you install to /dev/sda first, boot that, and then follow them for /dev/mmcblk0.

If you want to silence the log spam in the console you can either generate a new kernel, or set systemd loglevel to 'quiet' in /etc/rc.sysinit

**Comment by shdriesner** [comment]
Why does your approach use 4 disk partitions versus the samsung chromebook's approach of using only 2?  Is this a simplification you are also adopting?

**Comment by omgmog** [comment]
The reason we use 4 partitions is because of installing to eMMC. The process was [derived from a process](https://gist.github.com/abtrout/8403647) that used the following for installing to eMMC:

- partition 1:  u-boot
- partition 2:  kernel
- partition 3:  root (arch linux)
- partition 12: files for u-boot 

This structure is mainly due to where u-boot is configured to find `boot.scr.uimg`. When booting, u-boot searches all mountable partitions for `boot.scr.uimg`, so we have this on partition 12.

The [newer ArchLinuxARM process](http://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook) for USB just uses the following:

- partition 1: kernel
- partition 2: root (arch linux)

This is because when installing to USB you are using the u-boot and u-boot files located on the eMMC (from Chromeos), and I believe the stock u-boot looks for a `boot.scr.uimg` on the root partition (in `/dev/sda3/boot/boot.scr.uimg`).

Any new process will still require the u-boot partition, but we should be able to stick the `boot.scr.uimg` on the root of any of the other partitions, or maybe even create a symlink pointing to `/dev/mmc0blk3/boot/boot.scr.uimg`.

This would be entirely down to how u-boot is configured.

The annoying thing about this whole process is that if the slightest thing gets messed up, it's a cumbersome process to get back to the point that you can try again:

1. Create a ChromeOS recovery USB using another computer
2. Reinstall ChromeOS
3. Enable developer mode (which is another reinstall)
4. Enable booting from USB
5. Boot from  your prepared Arch USB and do all the things

**Comment by wamserma** [comment]
I modified the script to reflect the newer process. I will go for testing eMMC install next, but am still confused on how the partition on the eMMC should look like and what goes where.

The script might need a bit cleaning (vmlinux.uimg is not required any more, right?). I also added a few line to pluck crossystem and mosys from ChromeOS so we can re-enable USB-Boot after installing to eMMC. I'm probalby not the only one who accidentally updates systemd. :)
See also https://github.com/omgmog/archarm-usb-hp-chromebook-11/issues/47 for that.

**Comment by omgmog** [comment]
Should just need:

- `u-boot files` 8mb (fat16/ext2)
- `kernel` 32mb (kernel)
- `root` remaining space (ext4)

`u-boot files` would just contain an `env.txt` if needed (http://linux-exynos.org/wiki/ARM_Chromebook/U-Boot_Environment#Importing_an_environment)

If `root` is ext2, you could probably do without the `u-boot files` partition.

I spent the weekend dicking around with cross-compiling kernels (chromium, 3.8 kernel) and debootstrapping a rootfs (non Arch), with some success, but I'm now waiting for some parts to arrive from Amazon to permanently install a 32gb microSD inside the Chromebook (via USB)

**Comment by hitechredneck** [comment]
@wamserma I'll give the new script a go on my HP Chromebook 11

@omgmog this helps a lot, been doing the same messing with kernels and whatnot. Will report back results, if any.

**Comment by hitechredneck** [comment]
USB install works flawlessly with @wamserma 
Made a short url  http://git.io/vnlH2

The emmc install hangs with a file conflict with /user/bin/crossystem but renaming to /user/bin/crosystem.bak seems to resolve this. Beyond that still missing vmlinux.uimg and fails.

**Comment by wamserma** [comment]
MMC install works with script from @starkers  - I only had to add the download of a working cgpt from @omgmog's script. See http://git.io/vcNSH

**Comment by hitechredneck** [comment]
@wamserma confirmed working for MMC install using http://git.io/vcNSH
